networks:
  kafka_red:
    driver: bridge

services:
  kafka:
    build:
      context: miDockerfile
      dockerfile: Dockerfile
    networks:
      - kafka_red
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181