services:
  db:
    image: mysql
    container_name: mi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./inicializar.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - almacenardatos_kafka_red
volumes:
  db_data:
networks:
  almacenardatos_kafka_red:
    external: true